.yarn:
  tags:
    - node
    - yarn

cache:
  paths:
    - node_modules/

before_script:
  - node -v
  - yarn install

audit:
  extends: .yarn
  script:
    - yarn audit

deploy:
  extends: .yarn
  stage: deploy
  script:
    - ssh_wrap ssh node@theater-kaisersesch.de "cd /home/node/FasT-node && git pull && service fast_node restart"
  environment:
    name: production
  only:
    refs:
      - master
  when: manual
